//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SySTarjetasModel", "FK_Tarjeta_Banco", "Banco", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SySTarjetas.Core.Banco), "Tarjeta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SySTarjetas.Core.Tarjeta))]
[assembly: EdmRelationshipAttribute("SySTarjetasModel", "FK_Transaccion_Comercio", "Comercio", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SySTarjetas.Core.Comercio), "Transaccion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SySTarjetas.Core.Transaccion))]
[assembly: EdmRelationshipAttribute("SySTarjetasModel", "FK_Tarjeta_TipoTarjeta", "TipoTarjeta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SySTarjetas.Core.TipoTarjeta), "Tarjeta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SySTarjetas.Core.Tarjeta))]
[assembly: EdmRelationshipAttribute("SySTarjetasModel", "FK_Tarjeta_Titular", "Titular", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SySTarjetas.Core.Titular), "Tarjeta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SySTarjetas.Core.Tarjeta))]
[assembly: EdmRelationshipAttribute("SySTarjetasModel", "FK_TarjetaFechaCierre_Tarjeta", "Tarjeta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SySTarjetas.Core.Tarjeta), "TarjetaFechaCierre", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SySTarjetas.Core.TarjetaFechaCierre))]
[assembly: EdmRelationshipAttribute("SySTarjetasModel", "FK_TarjetaOpcionCierre_Tarjeta", "Tarjeta", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SySTarjetas.Core.Tarjeta), "TarjetaOpcionCierre", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SySTarjetas.Core.TarjetaOpcionCierre))]
[assembly: EdmRelationshipAttribute("SySTarjetasModel", "FK_Transaccion_Tarjeta", "Tarjeta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SySTarjetas.Core.Tarjeta), "Transaccion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SySTarjetas.Core.Transaccion))]
[assembly: EdmRelationshipAttribute("SySTarjetasModel", "FK_Transaccion_TarjetaFechaCierre", "TarjetaFechaCierre", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SySTarjetas.Core.TarjetaFechaCierre), "Transaccion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SySTarjetas.Core.Transaccion))]
[assembly: EdmRelationshipAttribute("SySTarjetasModel", "FK_TransaccionCuota_Transaccion", "Transaccion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SySTarjetas.Core.Transaccion), "TransaccionCuota", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SySTarjetas.Core.TransaccionCuota))]

#endregion

namespace SySTarjetas.Core
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SySTarjetasEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SySTarjetasEntities object using the connection string found in the 'SySTarjetasEntities' section of the application configuration file.
        /// </summary>
        public SySTarjetasEntities() : base("name=SySTarjetasEntities", "SySTarjetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SySTarjetasEntities object.
        /// </summary>
        public SySTarjetasEntities(string connectionString) : base(connectionString, "SySTarjetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SySTarjetasEntities object.
        /// </summary>
        public SySTarjetasEntities(EntityConnection connection) : base(connection, "SySTarjetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Banco> Banco
        {
            get
            {
                if ((_Banco == null))
                {
                    _Banco = base.CreateObjectSet<Banco>("Banco");
                }
                return _Banco;
            }
        }
        private ObjectSet<Banco> _Banco;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comercio> Comercio
        {
            get
            {
                if ((_Comercio == null))
                {
                    _Comercio = base.CreateObjectSet<Comercio>("Comercio");
                }
                return _Comercio;
            }
        }
        private ObjectSet<Comercio> _Comercio;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tarjeta> Tarjeta
        {
            get
            {
                if ((_Tarjeta == null))
                {
                    _Tarjeta = base.CreateObjectSet<Tarjeta>("Tarjeta");
                }
                return _Tarjeta;
            }
        }
        private ObjectSet<Tarjeta> _Tarjeta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TarjetaFechaCierre> TarjetaFechaCierre
        {
            get
            {
                if ((_TarjetaFechaCierre == null))
                {
                    _TarjetaFechaCierre = base.CreateObjectSet<TarjetaFechaCierre>("TarjetaFechaCierre");
                }
                return _TarjetaFechaCierre;
            }
        }
        private ObjectSet<TarjetaFechaCierre> _TarjetaFechaCierre;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TarjetaOpcionCierre> TarjetaOpcionCierre
        {
            get
            {
                if ((_TarjetaOpcionCierre == null))
                {
                    _TarjetaOpcionCierre = base.CreateObjectSet<TarjetaOpcionCierre>("TarjetaOpcionCierre");
                }
                return _TarjetaOpcionCierre;
            }
        }
        private ObjectSet<TarjetaOpcionCierre> _TarjetaOpcionCierre;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoTarjeta> TipoTarjeta
        {
            get
            {
                if ((_TipoTarjeta == null))
                {
                    _TipoTarjeta = base.CreateObjectSet<TipoTarjeta>("TipoTarjeta");
                }
                return _TipoTarjeta;
            }
        }
        private ObjectSet<TipoTarjeta> _TipoTarjeta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Titular> Titular
        {
            get
            {
                if ((_Titular == null))
                {
                    _Titular = base.CreateObjectSet<Titular>("Titular");
                }
                return _Titular;
            }
        }
        private ObjectSet<Titular> _Titular;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Transaccion> Transaccion
        {
            get
            {
                if ((_Transaccion == null))
                {
                    _Transaccion = base.CreateObjectSet<Transaccion>("Transaccion");
                }
                return _Transaccion;
            }
        }
        private ObjectSet<Transaccion> _Transaccion;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TransaccionCuota> TransaccionCuota
        {
            get
            {
                if ((_TransaccionCuota == null))
                {
                    _TransaccionCuota = base.CreateObjectSet<TransaccionCuota>("TransaccionCuota");
                }
                return _TransaccionCuota;
            }
        }
        private ObjectSet<TransaccionCuota> _TransaccionCuota;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Banco EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBanco(Banco banco)
        {
            base.AddObject("Banco", banco);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comercio EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComercio(Comercio comercio)
        {
            base.AddObject("Comercio", comercio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tarjeta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTarjeta(Tarjeta tarjeta)
        {
            base.AddObject("Tarjeta", tarjeta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TarjetaFechaCierre EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTarjetaFechaCierre(TarjetaFechaCierre tarjetaFechaCierre)
        {
            base.AddObject("TarjetaFechaCierre", tarjetaFechaCierre);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TarjetaOpcionCierre EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTarjetaOpcionCierre(TarjetaOpcionCierre tarjetaOpcionCierre)
        {
            base.AddObject("TarjetaOpcionCierre", tarjetaOpcionCierre);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoTarjeta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoTarjeta(TipoTarjeta tipoTarjeta)
        {
            base.AddObject("TipoTarjeta", tipoTarjeta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Titular EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTitular(Titular titular)
        {
            base.AddObject("Titular", titular);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Transaccion EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransaccion(Transaccion transaccion)
        {
            base.AddObject("Transaccion", transaccion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TransaccionCuota EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransaccionCuota(TransaccionCuota transaccionCuota)
        {
            base.AddObject("TransaccionCuota", transaccionCuota);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SySTarjetasModel", Name="Banco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Banco : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Banco object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="razonSocial">Initial value of the RazonSocial property.</param>
        public static Banco CreateBanco(global::System.Int32 id, global::System.String razonSocial)
        {
            Banco banco = new Banco();
            banco.Id = id;
            banco.RazonSocial = razonSocial;
            return banco;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, false, "RazonSocial");
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumeroSucursal
        {
            get
            {
                return _NumeroSucursal;
            }
            set
            {
                OnNumeroSucursalChanging(value);
                ReportPropertyChanging("NumeroSucursal");
                _NumeroSucursal = StructuralObject.SetValidValue(value, "NumeroSucursal");
                ReportPropertyChanged("NumeroSucursal");
                OnNumeroSucursalChanged();
            }
        }
        private Nullable<global::System.Int32> _NumeroSucursal;
        partial void OnNumeroSucursalChanging(Nullable<global::System.Int32> value);
        partial void OnNumeroSucursalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUIT
        {
            get
            {
                return _CUIT;
            }
            set
            {
                OnCUITChanging(value);
                ReportPropertyChanging("CUIT");
                _CUIT = StructuralObject.SetValidValue(value, true, "CUIT");
                ReportPropertyChanged("CUIT");
                OnCUITChanged();
            }
        }
        private global::System.String _CUIT;
        partial void OnCUITChanging(global::System.String value);
        partial void OnCUITChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true, "Direccion");
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Tarjeta_Banco", "Tarjeta")]
        public EntityCollection<Tarjeta> Tarjeta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tarjeta>("SySTarjetasModel.FK_Tarjeta_Banco", "Tarjeta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tarjeta>("SySTarjetasModel.FK_Tarjeta_Banco", "Tarjeta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SySTarjetasModel", Name="Comercio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comercio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comercio object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="razonSocial">Initial value of the RazonSocial property.</param>
        public static Comercio CreateComercio(global::System.Int32 id, global::System.String razonSocial)
        {
            Comercio comercio = new Comercio();
            comercio.Id = id;
            comercio.RazonSocial = razonSocial;
            return comercio;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, false, "RazonSocial");
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUIT
        {
            get
            {
                return _CUIT;
            }
            set
            {
                OnCUITChanging(value);
                ReportPropertyChanging("CUIT");
                _CUIT = StructuralObject.SetValidValue(value, true, "CUIT");
                ReportPropertyChanged("CUIT");
                OnCUITChanged();
            }
        }
        private global::System.String _CUIT;
        partial void OnCUITChanging(global::System.String value);
        partial void OnCUITChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true, "Direccion");
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Transaccion_Comercio", "Transaccion")]
        public EntityCollection<Transaccion> Transaccion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaccion>("SySTarjetasModel.FK_Transaccion_Comercio", "Transaccion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaccion>("SySTarjetasModel.FK_Transaccion_Comercio", "Transaccion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SySTarjetasModel", Name="Tarjeta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tarjeta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tarjeta object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="numeroTarjeta">Initial value of the NumeroTarjeta property.</param>
        /// <param name="fechaVencimiento">Initial value of the FechaVencimiento property.</param>
        public static Tarjeta CreateTarjeta(global::System.Int32 id, global::System.String numeroTarjeta, global::System.DateTime fechaVencimiento)
        {
            Tarjeta tarjeta = new Tarjeta();
            tarjeta.Id = id;
            tarjeta.NumeroTarjeta = numeroTarjeta;
            tarjeta.FechaVencimiento = fechaVencimiento;
            return tarjeta;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NumeroTarjeta
        {
            get
            {
                return _NumeroTarjeta;
            }
            set
            {
                OnNumeroTarjetaChanging(value);
                ReportPropertyChanging("NumeroTarjeta");
                _NumeroTarjeta = StructuralObject.SetValidValue(value, false, "NumeroTarjeta");
                ReportPropertyChanged("NumeroTarjeta");
                OnNumeroTarjetaChanged();
            }
        }
        private global::System.String _NumeroTarjeta;
        partial void OnNumeroTarjetaChanging(global::System.String value);
        partial void OnNumeroTarjetaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroCuenta
        {
            get
            {
                return _NumeroCuenta;
            }
            set
            {
                OnNumeroCuentaChanging(value);
                ReportPropertyChanging("NumeroCuenta");
                _NumeroCuenta = StructuralObject.SetValidValue(value, true, "NumeroCuenta");
                ReportPropertyChanged("NumeroCuenta");
                OnNumeroCuentaChanged();
            }
        }
        private global::System.String _NumeroCuenta;
        partial void OnNumeroCuentaChanging(global::System.String value);
        partial void OnNumeroCuentaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaVencimiento
        {
            get
            {
                return _FechaVencimiento;
            }
            set
            {
                OnFechaVencimientoChanging(value);
                ReportPropertyChanging("FechaVencimiento");
                _FechaVencimiento = StructuralObject.SetValidValue(value, "FechaVencimiento");
                ReportPropertyChanged("FechaVencimiento");
                OnFechaVencimientoChanged();
            }
        }
        private global::System.DateTime _FechaVencimiento;
        partial void OnFechaVencimientoChanging(global::System.DateTime value);
        partial void OnFechaVencimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LimiteCompra
        {
            get
            {
                return _LimiteCompra;
            }
            set
            {
                OnLimiteCompraChanging(value);
                ReportPropertyChanging("LimiteCompra");
                _LimiteCompra = StructuralObject.SetValidValue(value, "LimiteCompra");
                ReportPropertyChanged("LimiteCompra");
                OnLimiteCompraChanged();
            }
        }
        private Nullable<global::System.Decimal> _LimiteCompra;
        partial void OnLimiteCompraChanging(Nullable<global::System.Decimal> value);
        partial void OnLimiteCompraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LimiteFinanciacion
        {
            get
            {
                return _LimiteFinanciacion;
            }
            set
            {
                OnLimiteFinanciacionChanging(value);
                ReportPropertyChanging("LimiteFinanciacion");
                _LimiteFinanciacion = StructuralObject.SetValidValue(value, "LimiteFinanciacion");
                ReportPropertyChanged("LimiteFinanciacion");
                OnLimiteFinanciacionChanged();
            }
        }
        private Nullable<global::System.Decimal> _LimiteFinanciacion;
        partial void OnLimiteFinanciacionChanging(Nullable<global::System.Decimal> value);
        partial void OnLimiteFinanciacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value, "Active");
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Tarjeta_Banco", "Banco")]
        public Banco Banco
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Banco>("SySTarjetasModel.FK_Tarjeta_Banco", "Banco").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Banco>("SySTarjetasModel.FK_Tarjeta_Banco", "Banco").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Banco> BancoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Banco>("SySTarjetasModel.FK_Tarjeta_Banco", "Banco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Banco>("SySTarjetasModel.FK_Tarjeta_Banco", "Banco", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Tarjeta_TipoTarjeta", "TipoTarjeta")]
        public TipoTarjeta TipoTarjeta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoTarjeta>("SySTarjetasModel.FK_Tarjeta_TipoTarjeta", "TipoTarjeta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoTarjeta>("SySTarjetasModel.FK_Tarjeta_TipoTarjeta", "TipoTarjeta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoTarjeta> TipoTarjetaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoTarjeta>("SySTarjetasModel.FK_Tarjeta_TipoTarjeta", "TipoTarjeta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoTarjeta>("SySTarjetasModel.FK_Tarjeta_TipoTarjeta", "TipoTarjeta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Tarjeta_Titular", "Titular")]
        public Titular Titular
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Titular>("SySTarjetasModel.FK_Tarjeta_Titular", "Titular").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Titular>("SySTarjetasModel.FK_Tarjeta_Titular", "Titular").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Titular> TitularReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Titular>("SySTarjetasModel.FK_Tarjeta_Titular", "Titular");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Titular>("SySTarjetasModel.FK_Tarjeta_Titular", "Titular", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_TarjetaFechaCierre_Tarjeta", "TarjetaFechaCierre")]
        public EntityCollection<TarjetaFechaCierre> TarjetaFechaCierre
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TarjetaFechaCierre>("SySTarjetasModel.FK_TarjetaFechaCierre_Tarjeta", "TarjetaFechaCierre");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TarjetaFechaCierre>("SySTarjetasModel.FK_TarjetaFechaCierre_Tarjeta", "TarjetaFechaCierre", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_TarjetaOpcionCierre_Tarjeta", "TarjetaOpcionCierre")]
        public EntityCollection<TarjetaOpcionCierre> TarjetaOpcionCierre
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TarjetaOpcionCierre>("SySTarjetasModel.FK_TarjetaOpcionCierre_Tarjeta", "TarjetaOpcionCierre");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TarjetaOpcionCierre>("SySTarjetasModel.FK_TarjetaOpcionCierre_Tarjeta", "TarjetaOpcionCierre", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Transaccion_Tarjeta", "Transaccion")]
        public EntityCollection<Transaccion> Transaccion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaccion>("SySTarjetasModel.FK_Transaccion_Tarjeta", "Transaccion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaccion>("SySTarjetasModel.FK_Transaccion_Tarjeta", "Transaccion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SySTarjetasModel", Name="TarjetaFechaCierre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TarjetaFechaCierre : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TarjetaFechaCierre object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fechaCierre">Initial value of the FechaCierre property.</param>
        /// <param name="mes">Initial value of the Mes property.</param>
        /// <param name="anio">Initial value of the Anio property.</param>
        public static TarjetaFechaCierre CreateTarjetaFechaCierre(global::System.Int32 id, global::System.DateTime fechaCierre, global::System.Int32 mes, global::System.Int32 anio)
        {
            TarjetaFechaCierre tarjetaFechaCierre = new TarjetaFechaCierre();
            tarjetaFechaCierre.Id = id;
            tarjetaFechaCierre.FechaCierre = fechaCierre;
            tarjetaFechaCierre.Mes = mes;
            tarjetaFechaCierre.Anio = anio;
            return tarjetaFechaCierre;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCierre
        {
            get
            {
                return _FechaCierre;
            }
            set
            {
                OnFechaCierreChanging(value);
                ReportPropertyChanging("FechaCierre");
                _FechaCierre = StructuralObject.SetValidValue(value, "FechaCierre");
                ReportPropertyChanged("FechaCierre");
                OnFechaCierreChanged();
            }
        }
        private global::System.DateTime _FechaCierre;
        partial void OnFechaCierreChanging(global::System.DateTime value);
        partial void OnFechaCierreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Mes
        {
            get
            {
                return _Mes;
            }
            set
            {
                OnMesChanging(value);
                ReportPropertyChanging("Mes");
                _Mes = StructuralObject.SetValidValue(value, "Mes");
                ReportPropertyChanged("Mes");
                OnMesChanged();
            }
        }
        private global::System.Int32 _Mes;
        partial void OnMesChanging(global::System.Int32 value);
        partial void OnMesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Anio
        {
            get
            {
                return _Anio;
            }
            set
            {
                OnAnioChanging(value);
                ReportPropertyChanging("Anio");
                _Anio = StructuralObject.SetValidValue(value, "Anio");
                ReportPropertyChanged("Anio");
                OnAnioChanged();
            }
        }
        private global::System.Int32 _Anio;
        partial void OnAnioChanging(global::System.Int32 value);
        partial void OnAnioChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_TarjetaFechaCierre_Tarjeta", "Tarjeta")]
        public Tarjeta Tarjeta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarjeta>("SySTarjetasModel.FK_TarjetaFechaCierre_Tarjeta", "Tarjeta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarjeta>("SySTarjetasModel.FK_TarjetaFechaCierre_Tarjeta", "Tarjeta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tarjeta> TarjetaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarjeta>("SySTarjetasModel.FK_TarjetaFechaCierre_Tarjeta", "Tarjeta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tarjeta>("SySTarjetasModel.FK_TarjetaFechaCierre_Tarjeta", "Tarjeta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Transaccion_TarjetaFechaCierre", "Transaccion")]
        public EntityCollection<Transaccion> Transaccion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaccion>("SySTarjetasModel.FK_Transaccion_TarjetaFechaCierre", "Transaccion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaccion>("SySTarjetasModel.FK_Transaccion_TarjetaFechaCierre", "Transaccion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SySTarjetasModel", Name="TarjetaOpcionCierre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TarjetaOpcionCierre : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TarjetaOpcionCierre object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static TarjetaOpcionCierre CreateTarjetaOpcionCierre(global::System.Int32 id)
        {
            TarjetaOpcionCierre tarjetaOpcionCierre = new TarjetaOpcionCierre();
            tarjetaOpcionCierre.Id = id;
            return tarjetaOpcionCierre;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaDeSemana
        {
            get
            {
                return _DiaDeSemana;
            }
            set
            {
                OnDiaDeSemanaChanging(value);
                ReportPropertyChanging("DiaDeSemana");
                _DiaDeSemana = StructuralObject.SetValidValue(value, true, "DiaDeSemana");
                ReportPropertyChanged("DiaDeSemana");
                OnDiaDeSemanaChanged();
            }
        }
        private global::System.String _DiaDeSemana;
        partial void OnDiaDeSemanaChanging(global::System.String value);
        partial void OnDiaDeSemanaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Posicion
        {
            get
            {
                return _Posicion;
            }
            set
            {
                OnPosicionChanging(value);
                ReportPropertyChanging("Posicion");
                _Posicion = StructuralObject.SetValidValue(value, true, "Posicion");
                ReportPropertyChanged("Posicion");
                OnPosicionChanged();
            }
        }
        private global::System.String _Posicion;
        partial void OnPosicionChanging(global::System.String value);
        partial void OnPosicionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_TarjetaOpcionCierre_Tarjeta", "Tarjeta")]
        public Tarjeta Tarjeta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarjeta>("SySTarjetasModel.FK_TarjetaOpcionCierre_Tarjeta", "Tarjeta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarjeta>("SySTarjetasModel.FK_TarjetaOpcionCierre_Tarjeta", "Tarjeta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tarjeta> TarjetaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarjeta>("SySTarjetasModel.FK_TarjetaOpcionCierre_Tarjeta", "Tarjeta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tarjeta>("SySTarjetasModel.FK_TarjetaOpcionCierre_Tarjeta", "Tarjeta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SySTarjetasModel", Name="TipoTarjeta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoTarjeta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoTarjeta object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static TipoTarjeta CreateTipoTarjeta(global::System.Int32 id, global::System.String descripcion)
        {
            TipoTarjeta tipoTarjeta = new TipoTarjeta();
            tipoTarjeta.Id = id;
            tipoTarjeta.Descripcion = descripcion;
            return tipoTarjeta;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Tarjeta_TipoTarjeta", "Tarjeta")]
        public EntityCollection<Tarjeta> Tarjeta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tarjeta>("SySTarjetasModel.FK_Tarjeta_TipoTarjeta", "Tarjeta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tarjeta>("SySTarjetasModel.FK_Tarjeta_TipoTarjeta", "Tarjeta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SySTarjetasModel", Name="Titular")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Titular : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Titular object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dNI">Initial value of the DNI property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        public static Titular CreateTitular(global::System.Int32 id, global::System.String dNI, global::System.String apellido, global::System.String nombre)
        {
            Titular titular = new Titular();
            titular.Id = id;
            titular.DNI = dNI;
            titular.Apellido = apellido;
            titular.Nombre = nombre;
            return titular;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DNI
        {
            get
            {
                return _DNI;
            }
            set
            {
                OnDNIChanging(value);
                ReportPropertyChanging("DNI");
                _DNI = StructuralObject.SetValidValue(value, false, "DNI");
                ReportPropertyChanged("DNI");
                OnDNIChanged();
            }
        }
        private global::System.String _DNI;
        partial void OnDNIChanging(global::System.String value);
        partial void OnDNIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false, "Apellido");
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true, "Direccion");
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true, "Telefono");
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Tarjeta_Titular", "Tarjeta")]
        public EntityCollection<Tarjeta> Tarjeta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tarjeta>("SySTarjetasModel.FK_Tarjeta_Titular", "Tarjeta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tarjeta>("SySTarjetasModel.FK_Tarjeta_Titular", "Tarjeta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SySTarjetasModel", Name="Transaccion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transaccion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Transaccion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fechaCompra">Initial value of the FechaCompra property.</param>
        /// <param name="numeroCupon">Initial value of the NumeroCupon property.</param>
        /// <param name="cantidadCuotas">Initial value of the CantidadCuotas property.</param>
        /// <param name="importe">Initial value of the Importe property.</param>
        public static Transaccion CreateTransaccion(global::System.Int32 id, global::System.DateTime fechaCompra, global::System.Int32 numeroCupon, global::System.Int32 cantidadCuotas, global::System.Double importe)
        {
            Transaccion transaccion = new Transaccion();
            transaccion.Id = id;
            transaccion.FechaCompra = fechaCompra;
            transaccion.NumeroCupon = numeroCupon;
            transaccion.CantidadCuotas = cantidadCuotas;
            transaccion.Importe = importe;
            return transaccion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCompra
        {
            get
            {
                return _FechaCompra;
            }
            set
            {
                OnFechaCompraChanging(value);
                ReportPropertyChanging("FechaCompra");
                _FechaCompra = StructuralObject.SetValidValue(value, "FechaCompra");
                ReportPropertyChanged("FechaCompra");
                OnFechaCompraChanged();
            }
        }
        private global::System.DateTime _FechaCompra;
        partial void OnFechaCompraChanging(global::System.DateTime value);
        partial void OnFechaCompraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumeroCupon
        {
            get
            {
                return _NumeroCupon;
            }
            set
            {
                OnNumeroCuponChanging(value);
                ReportPropertyChanging("NumeroCupon");
                _NumeroCupon = StructuralObject.SetValidValue(value, "NumeroCupon");
                ReportPropertyChanged("NumeroCupon");
                OnNumeroCuponChanged();
            }
        }
        private global::System.Int32 _NumeroCupon;
        partial void OnNumeroCuponChanging(global::System.Int32 value);
        partial void OnNumeroCuponChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CantidadCuotas
        {
            get
            {
                return _CantidadCuotas;
            }
            set
            {
                OnCantidadCuotasChanging(value);
                ReportPropertyChanging("CantidadCuotas");
                _CantidadCuotas = StructuralObject.SetValidValue(value, "CantidadCuotas");
                ReportPropertyChanged("CantidadCuotas");
                OnCantidadCuotasChanged();
            }
        }
        private global::System.Int32 _CantidadCuotas;
        partial void OnCantidadCuotasChanging(global::System.Int32 value);
        partial void OnCantidadCuotasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observaciones
        {
            get
            {
                return _Observaciones;
            }
            set
            {
                OnObservacionesChanging(value);
                ReportPropertyChanging("Observaciones");
                _Observaciones = StructuralObject.SetValidValue(value, true, "Observaciones");
                ReportPropertyChanged("Observaciones");
                OnObservacionesChanged();
            }
        }
        private global::System.String _Observaciones;
        partial void OnObservacionesChanging(global::System.String value);
        partial void OnObservacionesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Importe
        {
            get
            {
                return _Importe;
            }
            set
            {
                OnImporteChanging(value);
                ReportPropertyChanging("Importe");
                _Importe = StructuralObject.SetValidValue(value, "Importe");
                ReportPropertyChanged("Importe");
                OnImporteChanged();
            }
        }
        private global::System.Double _Importe;
        partial void OnImporteChanging(global::System.Double value);
        partial void OnImporteChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Transaccion_Comercio", "Comercio")]
        public Comercio Comercio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comercio>("SySTarjetasModel.FK_Transaccion_Comercio", "Comercio").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comercio>("SySTarjetasModel.FK_Transaccion_Comercio", "Comercio").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Comercio> ComercioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comercio>("SySTarjetasModel.FK_Transaccion_Comercio", "Comercio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Comercio>("SySTarjetasModel.FK_Transaccion_Comercio", "Comercio", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Transaccion_Tarjeta", "Tarjeta")]
        public Tarjeta Tarjeta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarjeta>("SySTarjetasModel.FK_Transaccion_Tarjeta", "Tarjeta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarjeta>("SySTarjetasModel.FK_Transaccion_Tarjeta", "Tarjeta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tarjeta> TarjetaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarjeta>("SySTarjetasModel.FK_Transaccion_Tarjeta", "Tarjeta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tarjeta>("SySTarjetasModel.FK_Transaccion_Tarjeta", "Tarjeta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_Transaccion_TarjetaFechaCierre", "TarjetaFechaCierre")]
        public TarjetaFechaCierre TarjetaFechaCierre
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TarjetaFechaCierre>("SySTarjetasModel.FK_Transaccion_TarjetaFechaCierre", "TarjetaFechaCierre").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TarjetaFechaCierre>("SySTarjetasModel.FK_Transaccion_TarjetaFechaCierre", "TarjetaFechaCierre").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TarjetaFechaCierre> TarjetaFechaCierreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TarjetaFechaCierre>("SySTarjetasModel.FK_Transaccion_TarjetaFechaCierre", "TarjetaFechaCierre");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TarjetaFechaCierre>("SySTarjetasModel.FK_Transaccion_TarjetaFechaCierre", "TarjetaFechaCierre", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_TransaccionCuota_Transaccion", "TransaccionCuota")]
        public EntityCollection<TransaccionCuota> TransaccionCuota
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TransaccionCuota>("SySTarjetasModel.FK_TransaccionCuota_Transaccion", "TransaccionCuota");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TransaccionCuota>("SySTarjetasModel.FK_TransaccionCuota_Transaccion", "TransaccionCuota", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SySTarjetasModel", Name="TransaccionCuota")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TransaccionCuota : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TransaccionCuota object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="numeroCuota">Initial value of the NumeroCuota property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        /// <param name="importe">Initial value of the Importe property.</param>
        /// <param name="verificado">Initial value of the Verificado property.</param>
        public static TransaccionCuota CreateTransaccionCuota(global::System.Int32 id, global::System.Int32 numeroCuota, global::System.DateTime fecha, global::System.Double importe, global::System.Boolean verificado)
        {
            TransaccionCuota transaccionCuota = new TransaccionCuota();
            transaccionCuota.Id = id;
            transaccionCuota.NumeroCuota = numeroCuota;
            transaccionCuota.Fecha = fecha;
            transaccionCuota.Importe = importe;
            transaccionCuota.Verificado = verificado;
            return transaccionCuota;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumeroCuota
        {
            get
            {
                return _NumeroCuota;
            }
            set
            {
                OnNumeroCuotaChanging(value);
                ReportPropertyChanging("NumeroCuota");
                _NumeroCuota = StructuralObject.SetValidValue(value, "NumeroCuota");
                ReportPropertyChanged("NumeroCuota");
                OnNumeroCuotaChanged();
            }
        }
        private global::System.Int32 _NumeroCuota;
        partial void OnNumeroCuotaChanging(global::System.Int32 value);
        partial void OnNumeroCuotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value, "Fecha");
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Importe
        {
            get
            {
                return _Importe;
            }
            set
            {
                OnImporteChanging(value);
                ReportPropertyChanging("Importe");
                _Importe = StructuralObject.SetValidValue(value, "Importe");
                ReportPropertyChanged("Importe");
                OnImporteChanged();
            }
        }
        private global::System.Double _Importe;
        partial void OnImporteChanging(global::System.Double value);
        partial void OnImporteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Verificado
        {
            get
            {
                return _Verificado;
            }
            set
            {
                OnVerificadoChanging(value);
                ReportPropertyChanging("Verificado");
                _Verificado = StructuralObject.SetValidValue(value, "Verificado");
                ReportPropertyChanged("Verificado");
                OnVerificadoChanged();
            }
        }
        private global::System.Boolean _Verificado;
        partial void OnVerificadoChanging(global::System.Boolean value);
        partial void OnVerificadoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SySTarjetasModel", "FK_TransaccionCuota_Transaccion", "Transaccion")]
        public Transaccion Transaccion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Transaccion>("SySTarjetasModel.FK_TransaccionCuota_Transaccion", "Transaccion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Transaccion>("SySTarjetasModel.FK_TransaccionCuota_Transaccion", "Transaccion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Transaccion> TransaccionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Transaccion>("SySTarjetasModel.FK_TransaccionCuota_Transaccion", "Transaccion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Transaccion>("SySTarjetasModel.FK_TransaccionCuota_Transaccion", "Transaccion", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
